# Generated by Django 6.0.7 on 2026-07-16 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siisto', '0002_cunto_calories_cunto_protein_jimicsi_taariikhda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cunto',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='cunto',
            name='nooca_cuntada',
        ),
        migrations.RemoveField(
            model_name='jimicsi',
            name='magaca_jimicsiga',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dherer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hadaf',
        ),
        migrations.RemoveField(
            model_name='routine90',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cunto',
            name='kalooriga',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cunto',
            name='magaca_cuntada',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cunto',
            name='sawirka_cuntada',
            field=models.ImageField(blank=True, null=True, upload_to='food_scans/'),
        ),
        migrations.AddField(
            model_name='jimicsi',
            name='muddada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jimicsi',
            name='nooca_jimicsiga',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jimicsi',
            name='sawir_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='miisaanka_hadafka',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='routine90',
            name='dhammaystiray',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routine90',
            name='qorshaha_cuntada',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routine90',
            name='qorshaha_jimicsiga',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cunto',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cunto',
            name='taariikhda',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jimicsi',
            name='taariikhda',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='miisaan_hadda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='miisaanka',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('taariikhda', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
