# Generated by Django 6.0.7 on 2026-07-17 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siisto', '0003_remove_cunto_calories_remove_cunto_nooca_cuntada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jimicsi',
            name='user',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='taariikhda',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='ai_response',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='routine90',
            old_name='dhammaystiray',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='weightlog',
            old_name='taariikhda',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user_message',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='miisaan_hadda',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='miisaanka_hadafka',
        ),
        migrations.RemoveField(
            model_name='routine90',
            name='maalinta',
        ),
        migrations.RemoveField(
            model_name='routine90',
            name='qorshaha_cuntada',
        ),
        migrations.RemoveField(
            model_name='routine90',
            name='qorshaha_jimicsiga',
        ),
        migrations.RemoveField(
            model_name='weightlog',
            name='miisaanka',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='routine90',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routine90',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weightlog',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cunto',
        ),
        migrations.DeleteModel(
            name='Jimicsi',
        ),
    ]
