# Generated by Django 6.0.7 on 2026-07-17 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siisto', '0004_remove_jimicsi_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('target_muscle', models.CharField(max_length=100)),
                ('correct_form_instructions', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='meal_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='workout_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image_url',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='fats',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_ai',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routine90',
            name='title',
            field=models.CharField(default='Routine Title', max_length=200),
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siisto.exerciselibrary'),
        ),
    ]
