# Generated by Django 6.0.7 on 2026-07-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siisto', '0005_exerciselibrary_rename_meal_name_meal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='miisaanka_yoolka',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
