# Generated by Django 6.0.7 on 2026-08-02 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siisto', '0006_profile_miisaanka_yoolka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='miisaanka_yoolka',
            new_name='goal_weight',
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siisto.exerciselibrary'),
        ),
    ]
