# Generated by Django 6.0.7 on 2026-08-05 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siisto', '0007_rename_somali_fields_to_english'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exerciselibrary',
            name='correct_form_instructions',
        ),
        migrations.RemoveField(
            model_name='exerciselibrary',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='goal_weight',
        ),
        migrations.RemoveField(
            model_name='routine90',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='routine90',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exerciselibrary',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exerciselibrary',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciselibrary',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='food_name',
            field=models.CharField(default='Healthy Meal', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='routine90',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='routine90',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workout',
            name='calories_burned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(default='General Workout', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='exerciselibrary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciselibrary',
            name='target_muscle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='routine90',
            name='title',
            field=models.CharField(default='90 Days Challenge', max_length=200),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='weight',
            field=models.FloatField(default=70.0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
