# Generated by Django 6.0.7 on 2026-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siisto', '0008_profile_is_pro_profile_pro_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselibrary',
            name='category',
            field=models.CharField(choices=[('Chest', 'Chest / Xabadka'), ('Back', 'Back / Dhabarka'), ('Shoulders', 'Shoulders / Garabka'), ('Arms', 'Arms / Gacmaha'), ('Legs', 'Legs / Lugaha'), ('Abs / Core', 'Abs & Core / Caloosha'), ('Cardio', 'Cardio / Wadnaha & Orodka')], default='Chest', max_length=50),
        ),
        migrations.AddField(
            model_name='exerciselibrary',
            name='default_duration',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='exerciselibrary',
            name='default_reps',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exerciselibrary',
            name='default_sets',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='exerciselibrary',
            name='subcategory',
            field=models.CharField(blank=True, default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='exerciselibrary',
            name='video_3d_url',
            field=models.CharField(blank=True, help_text='Pinterest, YouTube, or 3D Video animation link', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='workout',
            name='video_3d_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='weight_kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='exerciselibrary',
            name='correct_form_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exerciselibrary',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exerciselibrary',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exerciselibrary',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='exerciselibrary',
            name='target_muscle',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=15),
        ),
    ]
