# Generated by Django 6.0.7 on 2026-08-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siisto', '0008_remove_chatmessage_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciselibrary',
            options={'ordering': ['category', 'subcategory', 'name']},
        ),
        migrations.AddField(
            model_name='exerciselibrary',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='exerciselibrary',
            name='equipment',
            field=models.CharField(blank=True, help_text='e.g. Barbell, Dumbbell, Cable Machine, Bodyweight', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exerciselibrary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_images/'),
        ),
        migrations.AddField(
            model_name='exerciselibrary',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to a video demonstration (YouTube, Pinterest, etc.)', max_length=500, null=True),
        ),
    ]
