# Generated by Django 6.0.7 on 2026-08-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siisto', '0009_exerciselibrary_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='da_da',
            field=models.IntegerField(blank=True, help_text='Age in years', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dhererka',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hadafka',
            field=models.CharField(blank=True, help_text='Fitness Goal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='heerka_dhaqdhaqaaqa',
            field=models.CharField(blank=True, help_text='Activity Level', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='jinsiga',
            field=models.CharField(blank=True, choices=[('male', 'Lab / Male'), ('female', 'Dhedig / Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='miisaanka_yoolka',
            field=models.FloatField(blank=True, help_text='Target Goal Weight in kg', null=True),
        ),
    ]
