# Generated by Django 6.0.7 on 2026-08-25 12:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siisto', '0011_production_schema_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='exerciselibrary',
            options={'ordering': ['category', 'subcategory', 'name']},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='routine90',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='weightlog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exerciselibrary',
            name='video_3d_url',
            field=models.CharField(blank=True, help_text='Legacy: external video URL (overridden by video_file if both present)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(default='Meal', max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.FloatField(default=9.99),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('evc_plus', 'EVC Plus (Hormuud)'), ('zaad', 'Zaad (Telesom)'), ('sahal', 'Sahal (Golis)'), ('other', 'Other')], default='paypal', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan_name',
            field=models.CharField(default='Siisto Pro Monthly', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed / Paid'), ('pending', 'Pending / Waiting'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('none', 'No Experience'), ('less_1y', 'Less than 1 year'), ('1_3y', '1–3 years'), ('3_5y', '3–5 years'), ('5plus', '5+ years')], default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner / Bilowle'), ('intermediate', 'Intermediate / Dhexdhexaad'), ('advanced', 'Advanced / Horumarsan'), ('elite', 'Elite / Khabiir')], default='beginner', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hadafka',
            field=models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight / Miisaan Dhimis'), ('build_muscle', 'Build Muscle / Muruq Dhis'), ('maintain', 'Maintain / Joogteyn'), ('athletic_endurance', 'Athletic Endurance / Awood'), ('fat_loss', 'Fat Loss / Xoqid Dufanka'), ('muscle_gain', 'Muscle Gain / Kordhin Muruqa'), ('fitness', 'General Fitness / Caafimaad Guud')], help_text='Fitness Goal', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='heerka_dhaqdhaqaaqa',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary / Fadhiga kaliya'), ('moderate', 'Moderate / Dhaqdhaqaaq Dhexdhexaad ah'), ('active', 'Active / Firfircoon'), ('very_active', 'Very Active / Aad u firfircoon')], help_text='Activity Level', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jinsiga',
            field=models.CharField(blank=True, choices=[('male', 'Male / Lab'), ('female', 'Female / Dhedig')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='routine90',
            name='title',
            field=models.CharField(default='90-Day Fitness Challenge', max_length=200),
        ),
        migrations.AlterField(
            model_name='routine90',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_90', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=15, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(default='Workout', max_length=200),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
