# Generated by Django 6.0.7 on 2026-08-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siisto', '0012_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('so', 'Somali / Soomaali'), ('en', 'English'), ('ar', 'Arabic / العربية')], default='so', help_text='Preferred UI language', max_length=10),
        ),
    ]
